name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set image tag
      run: echo "IMAGE=jgcha/demo-app:${{ github.sha }}" >> $GITHUB_ENV

    - name: Docker Login
      run: echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

    - name: Build and Push Docker Image
      run: |
        docker build -t $IMAGE .
        docker push $IMAGE

    - name: Update K8s Manifest
      run: |
        sed -i -E "s|image: .*|image: $IMAGE|g" k8s/deployment.yaml
        git config --global user.name "jgcha"
        git config --global user.email "sean9887@github.com"
        git add k8s/deployment.yaml
        git commit -m "Update image to $IMAGE"
        git push
